"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import {
  Activity, ArrowRight, Building2, Check, CheckCircle2, ChevronDown, ChevronRight, Clipboard,
  Download, ExternalLink, FileSpreadsheet, Filter, Globe2, LayoutDashboard, MapPin, Menu, Phone,
  Plus, RefreshCw, Search, Settings, Target, X, XCircle
} from "lucide-react";
import type { Business, DiscoveryJob, LeadStatus, SearchInput, SearchRecord } from "@/lib/types";

type View = "dashboard" | "new" | "searches" | "leads" | "settings" | "progress" | "results";
const countries: Record<string, string[]> = {
  "United States": ["California", "Florida", "New York", "Tennessee", "Texas", "Washington"], Canada: ["Alberta", "British Columbia", "Ontario", "Quebec"],
  "New Zealand": ["Auckland", "Canterbury", "Otago", "Wellington"], "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"], India: ["Karnataka", "Kerala", "Maharashtra", "Tamil Nadu"], Australia: ["New South Wales", "Queensland", "Victoria", "Western Australia"]
};
const categories = ["Restaurants", "Cafes", "Plumbers", "HVAC contractors", "Roofers", "Electricians", "Salons", "Barbers", "Gyms", "Dentists", "Auto detailing", "Car repair", "Landscaping", "Cleaning services", "Photographers", "Interior designers", "Real estate agencies", "Event planners", "Hotels", "Travel agencies"];
const initialForm: SearchInput = { country: "New Zealand", state: "Canterbury", city: "Christchurch", category: "Plumbers", rawQuery: "Plumbers", resultCount: 25, websiteFilter: "any", businessStatus: "open", radiusKm: 15 };
let accessToken = "";
let browserSupabase: SupabaseClient | null = null;
function getBrowserSupabase() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) return null;
  browserSupabase ??= createClient(url, key);
  return browserSupabase;
}

function fetchJson<T>(url: string, options?: RequestInit): Promise<T> { const headers = new Headers(options?.headers); if (accessToken) headers.set("Authorization", `Bearer ${accessToken}`); return fetch(url, { ...options, headers }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Request failed"); return data; }); }

export function LocalLeadApp() {
  const [view, setView] = useState<View>("dashboard"); const [searches, setSearches] = useState<SearchRecord[]>([]); const [active, setActive] = useState<SearchRecord | null>(null); const [job, setJob] = useState<DiscoveryJob | null>(null); const [storageMode, setStorageMode] = useState("local-file"); const [sidebarOpen, setSidebarOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [needsAuth, setNeedsAuth] = useState(false);
  const loadSearches = useCallback(async () => { try { const data = await fetchJson<{ searches: SearchRecord[]; storageMode: string }>("/api/searches"); setSearches(data.searches); setStorageMode(data.storageMode); setNeedsAuth(false); } catch (e) { const message = e instanceof Error ? e.message : "Could not load searches"; if (message === "Unauthorized") setNeedsAuth(true); else setError(message); } finally { setLoading(false); } }, []);
  useEffect(() => { void (async () => { const client = getBrowserSupabase(); if (client) accessToken = (await client.auth.getSession()).data.session?.access_token ?? ""; await loadSearches(); })(); }, [loadSearches]);
  const openSearch = useCallback(async (id: string, forcedView?: View) => { const data = await fetchJson<{ search: SearchRecord; job: DiscoveryJob }>(`/api/searches/${id}`); setActive(data.search); setJob(data.job); setView(forcedView ?? (data.job.status === "completed" ? "results" : "progress")); setSidebarOpen(false); }, []);
  useEffect(() => { if (view !== "progress" || !active || ["completed", "failed", "cancelled"].includes(job?.status ?? "")) return; const timer = setInterval(() => { void openSearch(active.id, "progress"); }, 650); return () => clearInterval(timer); }, [view, active, job?.status, openSearch]);
  useEffect(() => { if (job?.status === "completed" && view === "progress" && active) { const timer = setTimeout(() => void openSearch(active.id, "results"), 900); return () => clearTimeout(timer); } }, [job?.status, view, active, openSearch]);
  async function begin(input: SearchInput) { setError(""); const { search } = await fetchJson<{ search: SearchRecord }>("/api/searches", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); setActive(search); setJob({ id: search.jobId, searchId: search.id, status: "queued", progress: 0, processed: 0, total: input.resultCount, events: [], createdAt: search.createdAt, updatedAt: search.updatedAt }); setView("progress"); await fetchJson(`/api/searches/${search.id}/start`, { method: "POST" }); await loadSearches(); }
  function navigate(next: View) { setView(next); setSidebarOpen(false); if (["dashboard", "searches", "leads"].includes(next)) void loadSearches(); }
  const counts = useMemo(() => { const businesses = searches.flatMap((s) => s.businesses); return { businesses: businesses.length, searches: searches.length, noWebsite: businesses.filter((b) => b.websiteStatus === "no_website").length, poor: businesses.filter((b) => (b.analysis?.qualityScore ?? 101) <= 55).length, high: businesses.filter((b) => b.leadScore.score >= 80).length, contacted: businesses.filter((b) => b.leadStatus === "contacted").length, interested: businesses.filter((b) => b.leadStatus === "interested").length, converted: businesses.filter((b) => b.leadStatus === "converted").length }; }, [searches]);
  if (needsAuth) return <AuthPage onAuthenticated={async (token) => { accessToken = token; setLoading(true); setNeedsAuth(false); await loadSearches(); }} />;
  return <div className="min-h-screen bg-[#ecebe5] lg:flex">
    <Sidebar view={view} open={sidebarOpen} onClose={() => setSidebarOpen(false)} onNavigate={navigate} />
    <main className="min-w-0 flex-1 lg:ml-56">
      <Topbar storageMode={storageMode} onMenu={() => setSidebarOpen(true)} onNew={() => navigate("new")} />
      <div className="mx-auto max-w-[1540px] px-4 py-5 sm:px-6 lg:px-8 lg:py-7">
        {error && <div role="alert" className="mb-5 flex items-center justify-between border-l-4 border-[#a33b32] bg-[#f8e9e5] px-4 py-3 text-sm text-[#7f2f29]"><span>{error}</span><button aria-label="Dismiss error" onClick={() => setError("")}><X size={17}/></button></div>}
        {view === "dashboard" && <Dashboard counts={counts} searches={searches} loading={loading} onNew={() => navigate("new")} onOpen={openSearch} />}
        {view === "new" && <NewSearch onStart={begin} onError={setError} />}
        {view === "progress" && active && job && <Progress search={active} job={job} onCancel={async () => { await fetchJson(`/api/jobs/${job.id}/cancel`, { method: "POST" }); await openSearch(active.id, "progress"); }} />}
        {view === "results" && active && <Results search={active} onRefresh={() => openSearch(active.id, "results")} />}
        {view === "searches" && <SearchHistory searches={searches} loading={loading} onOpen={openSearch} onNew={() => navigate("new")} />}
        {view === "leads" && <AllLeads searches={searches} onOpen={openSearch} />}
        {view === "settings" && <SettingsPage storageMode={storageMode} />}
      </div>
    </main>
  </div>;
}

function AuthPage({ onAuthenticated }: { onAuthenticated: (token: string) => Promise<void> }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [mode, setMode] = useState<"signin"|"signup">("signin"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); const client = getBrowserSupabase(); if (!client) { setMessage("Supabase browser environment variables are missing."); return; } setBusy(true); setMessage(""); const result = mode === "signin" ? await client.auth.signInWithPassword({ email, password }) : await client.auth.signUp({ email, password }); setBusy(false); if (result.error) { setMessage(result.error.message); return; } if (!result.data.session) { setMessage("Check your email to confirm the account, then sign in."); setMode("signin"); return; } await onAuthenticated(result.data.session.access_token); }
  return <main className="grid min-h-screen place-items-center bg-[#242924] p-5"><div className="w-full max-w-md border border-[#4a5149] bg-[#fffefa] p-7 sm:p-9"><div className="mb-9 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center bg-[#176b5b] text-white"><Building2 size={18}/></span><div><p className="text-base font-bold tracking-tight">LOCALLEAD</p><p className="text-xs text-[#70756e]">Prospect intelligence</p></div></div><p className="eyebrow">Workspace access</p><h1 className="mt-3 text-2xl font-semibold tracking-[-0.025em]">{mode === "signin" ? "Sign in to continue" : "Create your workspace"}</h1><p className="mt-2 text-sm leading-6 text-[#626760]">Use your Supabase account to access saved searches and leads.</p><form onSubmit={submit} className="mt-7 space-y-4"><Field label="Email"><input className="field" type="email" required autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com"/></Field><Field label="Password"><input className="field" type="password" required minLength={6} autoComplete={mode === "signin" ? "current-password" : "new-password"} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 6 characters"/></Field>{message && <p role="status" className="border-l-4 border-[#9a5c13] bg-[#faf0dd] p-3 text-xs leading-5 text-[#7d4b12]">{message}</p>}<button disabled={busy} className="btn-primary w-full">{busy ? <RefreshCw className="animate-spin" size={17}/> : null}{mode === "signin" ? "Sign in" : "Create account"}<ArrowRight size={17}/></button></form><button className="mt-5 w-full text-center text-sm font-medium text-[#626760] hover:text-[#176b5b]" onClick={() => { setMode(mode === "signin" ? "signup" : "signin"); setMessage(""); }}>{mode === "signin" ? "New here? Create an account" : "Already have an account? Sign in"}</button></div></main>;
}

function Sidebar({ view, open, onClose, onNavigate }: { view: View; open: boolean; onClose: () => void; onNavigate: (v: View) => void }) {
  const nav: [View, typeof LayoutDashboard, string][] = [["dashboard", LayoutDashboard, "Dashboard"], ["new", Plus, "New Search"], ["searches", Search, "My Searches"], ["leads", Target, "Leads"], ["settings", Settings, "Settings"]];
  return <><div onClick={onClose} className={`fixed inset-0 z-30 bg-[#1a1d1a]/50 transition lg:hidden ${open ? "opacity-100" : "pointer-events-none opacity-0"}`} />
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-56 flex-col border-r border-[#3d433d] bg-[#252a25] text-white transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-16 items-center justify-between border-b border-[#3d433d] px-5"><button onClick={() => onNavigate("dashboard")} className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center bg-[#e4b34c] text-[#252a25]"><Building2 size={15}/></span><span className="text-[13px] font-bold tracking-[0.12em]">LOCALLEAD</span></button><button className="lg:hidden" aria-label="Close menu" onClick={onClose}><X size={20}/></button></div>
      <div className="px-4 pb-2 pt-6 text-[10px] font-bold uppercase tracking-[0.18em] text-[#858d84]">Workspace</div>
      <nav className="flex-1 px-2">{nav.map(([key, Icon, label]) => { const active = view === key || (key === "searches" && view === "results"); return <button key={key} onClick={() => onNavigate(key)} className={`relative flex w-full items-center gap-3 px-3 py-2.5 text-left text-[13px] font-medium transition ${active ? "bg-[#333a34] text-white before:absolute before:inset-y-2 before:left-0 before:w-0.5 before:bg-[#e4b34c]" : "text-[#b6bcb5] hover:bg-[#2e342f] hover:text-white"}`}><Icon size={16}/>{label}{key === "new" && <span className="ml-auto text-[9px] font-bold uppercase tracking-widest text-[#d9b966]">Start</span>}</button>; })}</nav>
      <div className="border-t border-[#3d433d] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#858d84]">Workspace</p><p className="mt-2 truncate text-sm font-medium">Demo workspace</p><p className="mt-1 text-xs text-[#858d84]">Local development</p></div>
    </aside></>;
}

function Topbar({ storageMode, onMenu, onNew }: { storageMode: string; onMenu: () => void; onNew: () => void }) { return <header className="sticky top-0 z-20 flex h-14 items-center border-b border-[#d5d5cd] bg-[#fffefa]/95 px-4 backdrop-blur sm:px-6 lg:px-8"><button onClick={onMenu} className="mr-3 lg:hidden" aria-label="Open menu"><Menu size={21}/></button><div className="hidden text-[11px] font-bold uppercase tracking-[0.14em] text-[#737870] sm:block">Prospect intelligence / Workspace</div><div className="ml-auto flex items-center gap-4"><div className="flex items-center gap-2 text-xs font-medium text-[#626760]"><span className={`h-1.5 w-1.5 ${storageMode === "supabase" ? "bg-[#176b5b]" : "bg-[#b3792e]"}`}/>{storageMode === "supabase" ? "Supabase connected" : "Local demo storage"}</div><button onClick={onNew} className="btn-primary min-h-0 h-8 px-3"><Plus size={15}/>New search</button></div></header>; }

function Dashboard({ counts, searches, loading, onNew, onOpen }: { counts: Record<string, number>; searches: SearchRecord[]; loading: boolean; onNew: () => void; onOpen: (id: string) => void }) {
  const stats = [["Businesses", counts.businesses], ["No website", counts.noWebsite], ["High opportunity", counts.high], ["Converted", counts.converted]] as const;
  const leads = searches.flatMap((s) => s.businesses.map((b) => ({ ...b, searchName: s.name, parentId: s.id }))).sort((a, b) => b.leadScore.score - a.leadScore.score).slice(0, 5);
  return <div><div className="mb-7 flex flex-col justify-between gap-5 border-b border-[#aeb1a9] pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow">Workspace overview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em] text-[#1a1d1a]">Prospect research</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#626760]">A working view of discovery activity, qualification signals, and leads that need attention.</p></div><button onClick={onNew} className="btn-primary self-start"><Search size={16}/>Start discovery</button></div>
    <dl className="grid border-y border-[#d5d5cd] bg-[#fffefa] sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value], index) => <div className={`px-5 py-4 ${index ? "border-t border-[#d5d5cd] sm:border-t-0 sm:border-l" : ""} ${index === 2 ? "sm:border-l-0 xl:border-l" : ""}`} key={label}><dt className="text-[11px] font-bold uppercase tracking-[0.13em] text-[#737870]">{label}</dt><dd className="mono-number mt-2 text-2xl font-semibold tracking-tight">{value.toLocaleString()}</dd></div>)}</dl>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="border-t-2 border-[#242924] bg-[#fffefa]"><SectionTitle title="Recent searches" subtitle="Latest discovery jobs"/>{loading ? <SkeletonRows/> : searches.length ? <div className="divide-y divide-[#d5d5cd]">{searches.slice(0, 6).map((s) => <button key={s.id} onClick={() => onOpen(s.id)} className="grid w-full grid-cols-[1fr_auto] items-center gap-4 px-5 py-4 text-left transition hover:bg-[#f5f4ee] sm:grid-cols-[1.4fr_.8fr_auto]"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#1a1d1a]">{s.name}</p><p className="mt-1 truncate text-xs text-[#737870]">{[s.city, s.state, s.country].filter(Boolean).join(", ")}</p></div><p className="hidden text-xs text-[#626760] sm:block">{formatDate(s.createdAt)} · {s.businesses.length} results</p><div className="flex items-center gap-3"><StatusBadge status={s.status}/><ChevronRight size={16} className="text-[#92968f]"/></div></button>)}</div> : <Empty icon={Search} title="No searches yet" text="Choose a market and category to start building your research set." action="Create your first search" onAction={onNew}/>}</section>
      <section className="border-t-2 border-[#242924] bg-[#fffefa]"><SectionTitle title="Priority leads" subtitle="Highest opportunity score"/>{leads.length ? <div className="divide-y divide-[#d5d5cd]">{leads.map((b) => <button onClick={() => onOpen(b.parentId)} key={b.id} className="flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-[#f5f4ee]"><ScoreRing score={b.leadScore.score}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{b.name}</p><p className="mt-1 truncate text-xs text-[#737870]">{b.city} · {b.websiteStatus === "no_website" ? "No website" : b.analysis ? `${b.analysis.qualityScore}/100 site quality` : "Website unknown"}</p></div><ChevronRight size={16} className="text-[#92968f]"/></button>)}</div> : <Empty icon={Target} title="No priority leads" text="Qualified businesses will appear here as searches complete."/>}</section></div>
  </div>;
}

function NewSearch({ onStart, onError }: { onStart: (input: SearchInput) => Promise<void>; onError: (message: string) => void }) {
  const [form, setForm] = useState(initialForm); const [advanced, setAdvanced] = useState(false); const [submitting, setSubmitting] = useState(false); const [categoryOpen, setCategoryOpen] = useState(false);
  const set = <K extends keyof SearchInput>(key: K, value: SearchInput[K]) => setForm((f) => ({ ...f, [key]: value }));
  async function submit() { if (!form.city.trim() || !form.category.trim()) { onError("Choose a city and business category before starting."); return; } setSubmitting(true); try { await onStart({ ...form, rawQuery: form.category }); } catch (e) { onError(e instanceof Error ? e.message : "Could not start discovery"); setSubmitting(false); } }
  return <div className="mx-auto max-w-6xl"><div className="mb-7 border-b border-[#aeb1a9] pb-6"><p className="eyebrow">New research set</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em] text-[#1a1d1a]">Define a target market</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#626760]">Set the geography, business type, and qualification threshold. You can refine the saved results after discovery.</p></div>
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_290px]"><div className="border-t-2 border-[#242924] bg-[#fffefa]"><StepHeader number="01" title="Market" text="Choose a precise target location."/><div className="grid gap-5 px-5 pb-7 md:grid-cols-3 md:px-7"><Field label="Country"><select className="field" value={form.country} onChange={(e) => { set("country", e.target.value); set("state", countries[e.target.value]?.[0] ?? ""); }}><option value="">Select country</option>{Object.keys(countries).map((c) => <option key={c}>{c}</option>)}</select></Field><Field label="State / Region"><select className="field" value={form.state} onChange={(e) => set("state", e.target.value)}><option value="">Any region</option>{(countries[form.country] ?? []).map((r) => <option key={r}>{r}</option>)}</select></Field><Field label="City / Area"><input className="field" value={form.city} onChange={(e) => set("city", e.target.value)} placeholder="e.g. Christchurch"/></Field></div>
      <div className="border-t border-[#d5d5cd]"><StepHeader number="02" title="Business type" text="Select a category or enter your own."/><div className="relative px-5 pb-7 md:px-7"><label className="label">Business category</label><div className="relative"><Search className="absolute left-3.5 top-3 text-[#737870]" size={17}/><input className="field pl-11" value={form.category} onFocus={() => setCategoryOpen(true)} onChange={(e) => { set("category", e.target.value); setCategoryOpen(true); }} placeholder="Search categories or type your own"/>{categoryOpen && <div className="absolute z-10 mt-1 max-h-60 w-full overflow-auto border border-[#bfc2ba] bg-[#fffefa] p-1 shadow-[var(--shadow-overlay)]">{categories.filter((c) => c.toLowerCase().includes(form.category.toLowerCase()) || !form.category).slice(0, 9).map((c) => <button key={c} onClick={() => { set("category", c); setCategoryOpen(false); }} className="flex w-full items-center gap-3 px-3 py-2.5 text-left text-sm hover:bg-[#f5f4ee]"><Building2 size={15} className="text-[#737870]"/>{c}</button>)}</div>}</div><p className="mt-2 text-xs text-[#737870]">Custom categories work in demo mode. Geoapify uses its documented category mapping.</p></div></div>
      <div className="border-t border-[#d5d5cd]"><StepHeader number="03" title="Result volume" text="Choose the size of the prospect list."/><div className="flex flex-wrap gap-2 px-5 pb-7 md:px-7">{[25, 50, 100, 250, 500].map((count) => <button key={count} onClick={() => set("resultCount", count)} className={`h-10 min-w-16 border px-4 text-sm font-semibold transition ${form.resultCount === count ? "border-[#176b5b] bg-[#e2eee9] text-[#0f5548]" : "border-[#c8cac2] bg-[#fffefa] text-[#626760] hover:border-[#858a82]"}`}>{count}</button>)}<div className="relative"><input aria-label="Custom result count" type="number" min={1} max={500} value={form.resultCount} onChange={(e) => set("resultCount", Math.min(500, Math.max(1, Number(e.target.value))))} className="field w-24"/></div><p className="w-full pt-1 text-xs text-[#737870]">Estimated processing time: {Math.max(2, Math.ceil(form.resultCount / 20))}–{Math.max(4, Math.ceil(form.resultCount / 10))} seconds. Provider maximum: 500.</p></div></div>
      <div className="border-t border-[#d5d5cd]"><button className="flex w-full items-center gap-3 px-5 py-5 text-left md:px-7" onClick={() => setAdvanced(!advanced)}><Filter size={16} className="text-[#626760]"/><span className="flex-1"><span className="block text-sm font-semibold">Qualification filters</span><span className="mt-0.5 block text-xs text-[#737870]">Rating, reviews, website status, radius</span></span><ChevronDown size={18} className={`text-[#737870] transition ${advanced ? "rotate-180" : ""}`}/></button>{advanced && <div className="grid gap-5 px-5 pb-7 md:grid-cols-2 md:px-7 lg:grid-cols-4"><Field label="Minimum rating"><select className="field" value={form.minimumRating ?? ""} onChange={(e) => set("minimumRating", e.target.value ? Number(e.target.value) : undefined)}><option value="">Any</option>{[3.5,4,4.3,4.5,4.7].map((v) => <option key={v} value={v}>{v}+</option>)}</select></Field><Field label="Minimum reviews"><select className="field" value={form.minimumReviews ?? ""} onChange={(e) => set("minimumReviews", e.target.value ? Number(e.target.value) : undefined)}><option value="">Any</option>{[10,25,50,100,250,500].map((v) => <option key={v} value={v}>{v}+</option>)}</select></Field><Field label="Website status"><select className="field" value={form.websiteFilter} onChange={(e) => set("websiteFilter", e.target.value as SearchInput["websiteFilter"])}><option value="any">Any</option><option value="no_website">No website</option><option value="has_website">Has website</option></select></Field><Field label="Radius"><select className="field" value={form.radiusKm} onChange={(e) => set("radiusKm", Number(e.target.value))}>{[5,10,15,25,50].map((v) => <option key={v} value={v}>{v} km</option>)}</select></Field></div>}</div></div>
      <aside className="sticky top-20 border-t-2 border-[#242924] bg-[#fffefa] p-5"><p className="eyebrow">Research brief</p><div className="mt-5 space-y-5"><Summary label="Location" value={[form.city, form.state, form.country].filter(Boolean).join(", ")}/><Summary label="Business type" value={form.category}/><Summary label="Result target" value={String(form.resultCount)}/><Summary label="Qualification" value={[form.minimumRating ? `${form.minimumRating}+ rating` : "Any rating", form.minimumReviews ? `${form.minimumReviews}+ reviews` : "Any reviews"].join(" · ")}/></div><div className="mt-6 border-t border-[#d5d5cd] pt-5"><button onClick={submit} disabled={submitting} className="btn-primary w-full">{submitting ? <RefreshCw size={17} className="animate-spin"/> : <Search size={17}/>}Start discovery<ArrowRight size={17}/></button><p className="mt-3 text-xs leading-5 text-[#737870]">Results are saved automatically when the job completes.</p></div></aside>
    </div></div>;
}

function Progress({ search, job, onCancel }: { search: SearchRecord; job: DiscoveryJob; onCancel: () => void }) {
  const stages = [{ key: "discovering", label: "Discovering businesses", icon: Search }, { key: "enriching", label: "Checking websites", icon: Globe2 }, { key: "analyzing", label: "Analyzing website quality", icon: Activity }, { key: "scoring", label: "Scoring opportunities", icon: Target }];
  const order = ["queued", "discovering", "enriching", "analyzing", "scoring", "completed"]; const current = order.indexOf(job.status);
  return <div className="mx-auto max-w-5xl"><PageHeader eyebrow="Discovery in progress" title={search.name} description={`${[search.city, search.state, search.country].filter(Boolean).join(", ")} · Up to ${search.resultCount} businesses`}/>
    <div className="border-t-2 border-[#242924] bg-[#fffefa]"><div className="border-b border-[#d5d5cd] p-5 sm:p-7"><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-semibold">{job.status === "completed" ? "Discovery complete" : job.status === "failed" ? "Discovery failed" : job.status === "cancelled" ? "Discovery cancelled" : stages.find((s) => s.key === job.status)?.label ?? "Preparing discovery"}</p><p className="mt-1 text-xs text-[#737870]"><span className="mono-number">{job.processed} / {job.total}</span> businesses in this stage</p></div><span className="mono-number text-2xl font-semibold text-[#176b5b]">{job.progress}%</span></div><div className="h-1.5 overflow-hidden bg-[#e3e2dc]" role="progressbar" aria-label="Discovery progress" aria-valuenow={job.progress} aria-valuemin={0} aria-valuemax={100}><div className={`h-full transition-all duration-500 ${job.status === "failed" ? "bg-[#a33b32]" : job.status === "cancelled" ? "bg-[#858a82]" : "bg-[#176b5b]"}`} style={{ width: `${job.progress}%` }}/></div></div>
      <div className="grid border-b border-[#d5d5cd] sm:grid-cols-4">{stages.map((stage, stageIndex) => { const index = order.indexOf(stage.key); const done = current > index; const active = job.status === stage.key; const Icon = stage.icon; return <div key={stage.key} className={`flex items-center gap-3 border-b border-[#d5d5cd] p-4 last:border-b-0 sm:border-b-0 ${stageIndex ? "sm:border-l" : ""}`}><span className={`mono-number text-xs font-bold ${done || active ? "text-[#176b5b]" : "text-[#9a9e97]"}`}>{String(stageIndex + 1).padStart(2,"0")}</span>{done ? <Check size={15} className="text-[#176b5b]"/> : <Icon size={15} className={active ? "animate-pulse text-[#176b5b]" : "text-[#9a9e97]"}/>}<p className={`text-xs font-semibold ${done || active ? "text-[#252925]" : "text-[#858a82]"}`}>{stage.label}</p></div>; })}</div>
      <div className="grid gap-6 p-5 sm:p-7 md:grid-cols-[1fr_220px]"><div><h2 className="mb-4 text-xs font-bold uppercase tracking-[0.13em]">Live activity</h2><div className="max-h-72 divide-y divide-[#e2e2dc] overflow-auto">{[...job.events].reverse().map((event, i) => <div key={event.id} className="grid grid-cols-[12px_1fr_auto] gap-3 py-3"><span className={`mt-1 h-2 w-2 ${i === 0 && !["failed","cancelled"].includes(job.status) ? "animate-pulse bg-[#176b5b]" : "bg-[#9a9e97]"}`}/><p className="text-sm text-[#414640]">{event.message}</p><p className="mono-number text-[10px] text-[#858a82]">{new Date(event.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</p></div>)}</div></div><aside className="border-l border-[#d5d5cd] pl-5"><p className="text-xs leading-5 text-[#737870]">This job continues in the background. You can leave and reopen it from saved searches.</p>{!["completed","failed","cancelled"].includes(job.status) && <button onClick={onCancel} className="mt-4 text-xs font-semibold text-[#7f2f29] underline underline-offset-4">Cancel job</button>}{job.error && <div role="alert" className="mt-5 border-l-4 border-[#a33b32] bg-[#f8e9e5] p-4 text-sm text-[#7f2f29]">{job.error}</div>}</aside></div>
    </div></div>;
}

function Results({ search, onRefresh }: { search: SearchRecord; onRefresh: () => void }) {
  const [query, setQuery] = useState(""); const [website, setWebsite] = useState("any"); const [opportunity, setOpportunity] = useState("any"); const [status, setStatus] = useState("any"); const [sort, setSort] = useState<"score"|"rating"|"reviews"|"name">("score"); const [page, setPage] = useState(1); const [selected, setSelected] = useState<Set<string>>(new Set()); const [detail, setDetail] = useState<Business | null>(null); const pageSize = 10;
  const businesses = useMemo(() => search.businesses.filter((b) => `${b.name} ${b.category} ${b.city}`.toLowerCase().includes(query.toLowerCase()) && (website === "any" || (website === "poor" ? (b.analysis?.qualityScore ?? 101) <= 55 : b.websiteStatus === website)) && (opportunity === "any" || (opportunity === "high" ? b.leadScore.score >= 80 : opportunity === "medium" ? b.leadScore.score >= 40 && b.leadScore.score < 80 : b.leadScore.score < 40)) && (status === "any" || b.leadStatus === status)).sort((a,b) => sort === "score" ? b.leadScore.score - a.leadScore.score : sort === "rating" ? (b.rating ?? 0) - (a.rating ?? 0) : sort === "reviews" ? (b.reviewCount ?? 0) - (a.reviewCount ?? 0) : a.name.localeCompare(b.name)), [search.businesses, query, website, opportunity, status, sort]);
  const visible = businesses.slice((page - 1) * pageSize, page * pageSize); const pages = Math.max(1, Math.ceil(businesses.length / pageSize)); const stats = { noWebsite: search.businesses.filter((b) => b.websiteStatus === "no_website").length, poor: search.businesses.filter((b) => (b.analysis?.qualityScore ?? 101) <= 55).length, high: search.businesses.filter((b) => b.leadScore.score >= 80).length, average: search.businesses.reduce((s,b) => s + (b.rating ?? 0), 0) / Math.max(1, search.businesses.filter((b) => b.rating).length) };
  function exportData(format: "csv"|"xlsx", onlySelected = false) { const ids = onlySelected && selected.size ? `&ids=${[...selected].join(",")}` : ""; window.location.href = `/api/export/${search.id}?format=${format}${ids}`; }
  async function update(business: Business, patch: { leadStatus?: LeadStatus; notes?: string }) { await fetchJson(`/api/businesses/${business.id}?searchId=${search.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); setDetail(null); await onRefresh(); }
  return <div><PageHeader eyebrow="Search results" title={search.name} description={`${[search.city, search.state, search.country].filter(Boolean).join(", ")} · Completed ${formatDate(search.updatedAt)}`} action={<div className="flex flex-wrap gap-2"><button onClick={() => exportData("csv", selected.size > 0)} className="btn-secondary"><Download size={16}/>{selected.size ? `Export ${selected.size}` : "Export CSV"}</button><button onClick={() => exportData("xlsx", selected.size > 0)} className="btn-primary"><FileSpreadsheet size={16}/>Export XLSX</button></div>}/>
    <dl className="grid border-y border-[#d5d5cd] bg-[#fffefa] sm:grid-cols-2 xl:grid-cols-5">{[["Businesses", search.businesses.length], ["No website", stats.noWebsite], ["Poor website", stats.poor], ["High opportunity", stats.high], ["Average rating", stats.average ? stats.average.toFixed(1) : "—"]].map(([label, value], index) => <div className={`px-4 py-3 ${index ? "border-t border-[#d5d5cd] sm:border-l sm:border-t-0" : ""} ${index === 2 || index === 4 ? "sm:border-l-0 xl:border-l" : ""}`} key={label}><dt className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#737870]">{label}</dt><dd className="mono-number mt-1 text-xl font-semibold">{value}</dd></div>)}</dl>
    <div className="mt-6 overflow-hidden border-t-2 border-[#242924] bg-[#fffefa]"><div className="flex flex-col gap-3 border-b border-[#d5d5cd] p-4 xl:flex-row xl:items-center"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 text-[#737870]" size={16}/><input className="field h-9 pl-9" value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Search businesses, category, or location"/></div><div className="flex flex-wrap gap-2"><CompactSelect value={website} onChange={setWebsite} options={[["any","All websites"],["no_website","No website"],["has_website","Has website"],["poor","Poor website"]]}/><CompactSelect value={opportunity} onChange={setOpportunity} options={[["any","All opportunities"],["high","High"],["medium","Medium"],["low","Low"]]}/><CompactSelect value={status} onChange={setStatus} options={[["any","All statuses"],["new","New"],["contacted","Contacted"],["interested","Interested"],["converted","Converted"]]}/><CompactSelect value={sort} onChange={(v) => setSort(v as typeof sort)} options={[["score","Sort: Opportunity"],["rating","Sort: Rating"],["reviews","Sort: Reviews"],["name","Sort: Name"]]}/></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead><tr className="border-b border-[#bfc2ba] bg-[#f5f4ee] text-[10px] font-bold uppercase tracking-[0.13em] text-[#626760]"><th className="w-12 px-4 py-3"><input type="checkbox" aria-label="Select visible businesses" checked={visible.length > 0 && visible.every((b) => selected.has(b.id))} onChange={(e) => setSelected((old) => { const next = new Set(old); visible.forEach((b) => { if (e.target.checked) next.add(b.id); else next.delete(b.id); }); return next; })}/></th>{["Business","Category","Rating","Reviews","Location","Website","Quality","Opportunity","Phone","Status"].map((h) => <th className="px-3 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-[#d5d5cd]">{visible.map((b) => <tr key={b.id} className="cursor-pointer text-[13px] transition hover:bg-[#f5f4ee]" onClick={() => setDetail(b)}><td className="px-4 py-3" onClick={(e) => e.stopPropagation()}><input type="checkbox" aria-label={`Select ${b.name}`} checked={selected.has(b.id)} onChange={(e) => setSelected((old) => { const next = new Set(old); if (e.target.checked) next.add(b.id); else next.delete(b.id); return next; })}/></td><td className="max-w-60 px-3 py-3"><p className="truncate font-semibold text-[#1a1d1a]">{b.name}</p><p className="mt-1 truncate text-[11px] text-[#858a82]">{b.address}</p></td><td className="px-3 py-3 text-[#626760]">{b.category}</td><td className="mono-number px-3 py-3 font-semibold">{b.rating ?? "—"}</td><td className="mono-number px-3 py-3 text-[#626760]">{b.reviewCount ?? "—"}</td><td className="px-3 py-3 text-[#626760]">{b.city}</td><td className="px-3 py-3"><WebsiteBadge status={b.websiteStatus}/></td><td className="mono-number px-3 py-3">{b.analysis ? <span className={`font-semibold ${b.analysis.qualityScore <= 55 ? "text-[#9a5c13]" : "text-[#176b5b]"}`}>{b.analysis.qualityScore}/100</span> : "—"}</td><td className="px-3 py-3"><OpportunityBadge score={b.leadScore.score}/></td><td className="mono-number whitespace-nowrap px-3 py-3 text-[#626760]">{b.phone ?? "—"}</td><td className="px-3 py-3"><LeadStatusBadge status={b.leadStatus}/></td></tr>)}</tbody></table>{!visible.length && <Empty icon={Search} title="No matching leads" text="Try clearing one or more filters."/>}</div>
      <div className="flex items-center justify-between border-t border-gray-100 px-5 py-4"><p className="text-xs text-gray-500">Showing {visible.length ? (page - 1) * pageSize + 1 : 0}–{Math.min(page * pageSize, businesses.length)} of {businesses.length}</p><div className="flex items-center gap-2"><button className="btn-secondary h-8 px-3 py-0 text-xs" disabled={page === 1} onClick={() => setPage((p) => p - 1)}>Previous</button><span className="text-xs text-gray-500">{page} / {pages}</span><button className="btn-secondary h-8 px-3 py-0 text-xs" disabled={page === pages} onClick={() => setPage((p) => p + 1)}>Next</button></div></div>
    </div>{detail && <BusinessDrawer business={detail} onClose={() => setDetail(null)} onUpdate={update}/>}</div>;
}

function BusinessDrawer({ business: b, onClose, onUpdate }: { business: Business; onClose: () => void; onUpdate: (b: Business, patch: { leadStatus?: LeadStatus; notes?: string }) => Promise<void> }) {
  const [notes, setNotes] = useState(b.notes); const [saving, setSaving] = useState(false);
  async function save(patch: { leadStatus?: LeadStatus; notes?: string }) { setSaving(true); await onUpdate(b, patch); setSaving(false); }
  return <><div className="fixed inset-0 z-40 bg-[#1a1d1a]/40" onClick={onClose}/><aside aria-label="Business details" className="fixed inset-y-0 right-0 z-50 w-full max-w-[640px] overflow-y-auto border-l border-[#aeb1a9] bg-[#fffefa] shadow-[var(--shadow-overlay)]"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-[#d5d5cd] bg-[#fffefa]/95 p-5 backdrop-blur sm:p-6"><div><p className="eyebrow">Business record</p><div className="mt-3 flex items-center gap-2"><OpportunityBadge score={b.leadScore.score}/><LeadStatusBadge status={b.leadStatus}/></div><h2 className="mt-3 text-xl font-semibold tracking-[-0.02em]">{b.name}</h2><p className="mt-1 text-sm text-[#626760]">{b.category} · {b.city}</p></div><button aria-label="Close business details" onClick={onClose} className="grid h-9 w-9 place-items-center border border-[#d5d5cd] hover:bg-[#f5f4ee]"><X size={18}/></button></div>
    <div className="space-y-7 p-5 sm:p-6"><div className="grid grid-cols-3 border-y border-[#d5d5cd] py-4"><Metric label="Rating" value={b.rating ? `${b.rating} ★` : "—"}/><Metric label="Reviews" value={String(b.reviewCount ?? "—")}/><Metric label="Opportunity" value={`${b.leadScore.score}/100`}/></div>
      <section><h3 className="mb-3 text-xs font-bold uppercase tracking-[0.13em]">Business details</h3><div className="space-y-3 border-t border-[#d5d5cd] pt-4"><Info icon={MapPin} text={b.address}/><Info icon={Phone} text={b.phone ?? "No phone supplied"}/><Info icon={Globe2} text={b.websiteUrl ?? (b.websiteStatus === "uncertain" ? "Official website uncertain" : "No official website found")}/></div><div className="mt-4 flex flex-wrap gap-2">{b.mapsUrl && <a href={b.mapsUrl} target="_blank" rel="noreferrer" className="btn-secondary text-xs"><MapPin size={15}/>Open map</a>}{b.websiteUrl && <a href={b.websiteUrl} target="_blank" rel="noreferrer" className="btn-secondary text-xs"><ExternalLink size={15}/>Open website</a>}{b.phone && <button onClick={() => navigator.clipboard.writeText(b.phone!)} className="btn-secondary text-xs"><Clipboard size={15}/>Copy phone</button>}</div></section>
      <section><h3 className="mb-3 text-xs font-bold uppercase tracking-[0.13em]">Score evidence</h3><div className="divide-y divide-[#e2e2dc] border-y border-[#d5d5cd]">{b.leadScore.factors.length ? b.leadScore.factors.map((factor) => <div key={factor.label} className="flex items-center justify-between py-3 text-sm"><span className="text-[#626760]">{factor.label}</span><span className="mono-number font-semibold text-[#176b5b]">+{factor.points}</span></div>) : <p className="py-4 text-sm text-[#626760]">No strong opportunity signals were detected.</p>}</div></section>
      {b.analysis && <section><div className="mb-3 flex items-center justify-between"><h3 className="text-xs font-bold uppercase tracking-[0.13em]">Website analysis</h3><span className="mono-number text-sm font-bold">{b.analysis.qualityScore}/100</span></div><div className="grid border border-[#d5d5cd] sm:grid-cols-2">{[["HTTPS",b.analysis.httpsEnabled],["Mobile viewport",b.analysis.mobileFriendly],["Clear CTA",b.analysis.hasClearCta],["Contact form",b.analysis.hasContactForm],["Booking",b.analysis.hasBooking],["Meta description",b.analysis.hasMetaDescription],["Services explained",b.analysis.servicesExplained],["Social links",b.analysis.hasSocialLinks]].map(([label, ok], index) => <div key={String(label)} className={`flex items-center gap-2 border-[#d5d5cd] px-3 py-2.5 text-xs ${index > 0 ? "border-t" : ""} ${index % 2 ? "sm:border-l" : ""} ${index === 1 ? "sm:border-t-0" : ""}`}>{ok ? <CheckCircle2 size={14} className="text-[#176b5b]"/> : <XCircle size={14} className="text-[#9a5c13]"/>}<span>{label}</span></div>)}</div>{b.analysis.error && <p className="mt-3 border-l-4 border-[#9a5c13] bg-[#faf0dd] p-3 text-xs text-[#7d4b12]">Analysis note: {b.analysis.error}</p>}</section>}
      <section><h3 className="mb-3 text-sm font-semibold">Lead status</h3><select className="field" value={b.leadStatus} onChange={(e) => void save({ leadStatus: e.target.value as LeadStatus })}><option value="new">New</option><option value="contacted">Contacted</option><option value="interested">Interested</option><option value="not_interested">Not interested</option><option value="converted">Converted</option></select></section>
      <section><h3 className="mb-3 text-sm font-semibold">Notes</h3><textarea className="field h-28 resize-none py-3" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Add context, next steps, or outreach notes..."/><button disabled={saving || notes === b.notes} onClick={() => void save({ notes })} className="btn-primary mt-3">{saving ? "Saving…" : "Save note"}</button></section>
      <section><h3 className="mb-3 text-sm font-semibold">Timeline</h3><div className="space-y-4 border-l border-gray-200 pl-5"><Timeline label="Business discovered" time={b.createdAt}/>{b.analysis && <Timeline label="Website checked and analyzed" time={b.analysis.checkedAt}/>} {b.leadStatus !== "new" && <Timeline label={`Marked ${b.leadStatus.replace("_", " ")}`} time={b.updatedAt}/>}</div></section>
    </div></aside></>;
}

function SearchHistory({ searches, loading, onOpen, onNew }: { searches: SearchRecord[]; loading: boolean; onOpen: (id: string) => void; onNew: () => void }) { return <div><PageHeader eyebrow="Research library" title="Saved searches" description="Reopen discovery jobs and their persisted results." action={<button onClick={onNew} className="btn-primary"><Plus size={16}/>New search</button>}/><div className="border-t-2 border-[#242924] bg-[#fffefa]">{loading ? <SkeletonRows/> : searches.length ? <><div className="hidden grid-cols-[1.5fr_.8fr_.8fr_auto] border-b border-[#d5d5cd] px-5 py-3 text-[10px] font-bold uppercase tracking-[0.13em] text-[#737870] sm:grid"><span>Search</span><span>Created</span><span>Results</span><span>Status</span></div><div className="divide-y divide-[#d5d5cd]">{searches.map((s) => <button onClick={() => onOpen(s.id)} key={s.id} className="grid w-full grid-cols-[1fr_auto] items-center gap-4 p-5 text-left hover:bg-[#f5f4ee] sm:grid-cols-[1.5fr_.8fr_.8fr_auto]"><div><p className="font-semibold">{s.name}</p><p className="mt-1 text-xs text-[#737870]">{[s.city,s.state,s.country].filter(Boolean).join(", ")}</p></div><p className="hidden text-sm sm:block">{formatDate(s.createdAt)}</p><p className="hidden text-sm sm:block"><span className="mono-number">{s.businesses.length}</span> businesses · <span className="mono-number">{s.businesses.filter((b) => b.leadScore.score >= 80).length}</span> high</p><div className="flex items-center gap-3"><StatusBadge status={s.status}/><ChevronRight size={16} className="text-[#92968f]"/></div></button>)}</div></> : <Empty icon={Search} title="No saved searches" text="Every discovery job will be saved here." action="Start a search" onAction={onNew}/>}</div></div>; }
function AllLeads({ searches, onOpen }: { searches: SearchRecord[]; onOpen: (id: string) => void }) { const leads = searches.flatMap((s) => s.businesses.map((b) => ({ ...b, searchId: s.id, searchName: s.name }))).sort((a,b) => b.leadScore.score - a.leadScore.score); return <div><PageHeader eyebrow="Pipeline" title="All leads" description="Qualified businesses across every completed search."/><div className="border-t-2 border-[#242924] bg-[#fffefa]">{leads.length ? <><div className="hidden grid-cols-[70px_1.3fr_1fr_.7fr_auto] border-b border-[#d5d5cd] px-5 py-3 text-[10px] font-bold uppercase tracking-[0.13em] text-[#737870] sm:grid"><span>Score</span><span>Business</span><span>Source</span><span>Website</span><span>Status</span></div><div className="divide-y divide-[#d5d5cd]">{leads.slice(0,100).map((b) => <button key={b.id} onClick={() => onOpen(b.searchId)} className="grid w-full grid-cols-[auto_1fr_auto] items-center gap-4 p-5 text-left hover:bg-[#f5f4ee] sm:grid-cols-[70px_1.3fr_1fr_.7fr_auto]"><ScoreRing score={b.leadScore.score}/><div className="min-w-0"><p className="truncate font-semibold">{b.name}</p><p className="mt-1 text-xs text-[#737870] sm:hidden">{b.searchName}</p></div><p className="hidden truncate text-sm text-[#626760] sm:block">{b.searchName}</p><div className="hidden sm:block"><WebsiteBadge status={b.websiteStatus}/></div><div className="flex items-center gap-3"><LeadStatusBadge status={b.leadStatus}/><ChevronRight size={16} className="text-[#92968f]"/></div></button>)}</div></> : <Empty icon={Target} title="No leads yet" text="Run a search to begin qualifying prospects."/>}</div></div>; }
function SettingsPage({ storageMode }: { storageMode: string }) { return <div className="mx-auto max-w-5xl"><PageHeader eyebrow="Configuration" title="Workspace settings" description="Runtime connections, analysis policy, and export behavior."/><div className="border-t-2 border-[#242924] bg-[#fffefa] px-5 md:px-7"><SettingsCard icon={Building2} title="Workspace profile" text="LocalLead demo workspace"><p className="text-sm leading-6 text-[#626760]">Authentication is bypassed only while <code className="bg-[#efeee9] px-1.5 py-1 text-xs">DEMO_MODE=true</code>. Production API routes validate a Supabase access token.</p></SettingsCard><SettingsCard icon={Globe2} title="Data provider" text={storageMode === "supabase" ? "Supabase database connected" : "Mock provider · local memory store"}><div className="border-l-4 border-[#176b5b] bg-[#e2eee9] p-4 text-sm text-[#174f45]"><p className="font-semibold">{storageMode === "supabase" ? "Supabase is connected" : "Mock provider is active"}</p><p className="mt-1 text-xs leading-5">Set BUSINESS_DATA_PROVIDER=geoapify and GEOAPIFY_API_KEY on the server to use the real adapter. Required attribution is retained in job events.</p></div></SettingsCard><SettingsCard icon={Activity} title="Website analysis" text="Lightweight public-page checks"><p className="text-sm leading-6 text-[#626760]">Checks HTTPS, mobile viewport, metadata, contact links, forms, booking language, CTAs, service and location clarity, and social links. It does not bypass authentication, robots protections, CAPTCHAs, or rate limits.</p></SettingsCard><SettingsCard icon={FileSpreadsheet} title="Exports" text="CSV and Excel"><p className="text-sm leading-6 text-[#626760]">Exports include business, contact, website, quality, opportunity, pipeline status, map link, and notes fields.</p></SettingsCard></div></div>; }

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-5 border-b border-[#aeb1a9] pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">{title}</h1><p className="mt-2 text-sm leading-6 text-[#626760]">{description}</p></div>{action && <div className="self-start">{action}</div>}</div>; }

function StepHeader({ number, title, text }: { number: string; title: string; text: string }) { return <div className="flex items-start gap-4 px-5 pb-5 pt-7 md:px-7"><span className="mono-number shrink-0 pt-0.5 text-xs font-bold text-[#176b5b]">{number}</span><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-[#626760]">{text}</p></div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="label">{label}</span>{children}</label>; }
function Summary({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#737870]">{label}</p><p className="mt-1 text-sm font-semibold text-[#252925]">{value || "—"}</p></div>; }
function SectionTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div className="flex items-center justify-between border-b border-[#d5d5cd] px-5 py-4"><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-[#737870]">{subtitle}</p></div></div>; }
function Empty({ icon: Icon, title, text, action, onAction }: { icon: typeof Search; title: string; text: string; action?: string; onAction?: () => void }) { return <div className="px-6 py-12 text-center"><Icon size={20} className="mx-auto text-[#858a82]"/><h3 className="mt-4 text-sm font-semibold">{title}</h3><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-[#737870]">{text}</p>{action && <button onClick={onAction} className="mt-4 text-sm font-semibold text-[#176b5b] underline decoration-[#9ebdb4] underline-offset-4">{action}</button>}</div>; }
function SkeletonRows() { return <div className="divide-y divide-[#d5d5cd]">{[1,2,3].map((v) => <div key={v} className="animate-pulse px-5 py-5"><div className="h-3 w-1/3 bg-[#e8e7e1]"/><div className="mt-2 h-2.5 w-1/2 bg-[#efeee9]"/></div>)}</div>; }
function StatusBadge({ status }: { status: string }) { const done = status === "completed"; const bad = status === "failed" || status === "cancelled"; return <span className={`border-l-2 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${done ? "border-[#176b5b] text-[#176b5b]" : bad ? "border-[#a33b32] text-[#a33b32]" : "border-[#9a5c13] text-[#8a571b]"}`}>{status}</span>; }
function WebsiteBadge({ status }: { status: Business["websiteStatus"] }) { const config = status === "no_website" ? ["No website","border-[#b3792e] text-[#8a571b]"] : status === "has_website" ? ["Website","border-[#176b5b] text-[#176b5b]"] : status === "uncertain" ? ["Uncertain","border-[#858a82] text-[#626760]"] : ["Unknown","border-[#858a82] text-[#626760]"]; return <span className={`whitespace-nowrap border-l-2 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${config[1]}`}>{config[0]}</span>; }
function OpportunityBadge({ score }: { score: number }) { const style = score >= 80 ? "border-[#a33b32] text-[#8f332c]" : score >= 60 ? "border-[#b06228] text-[#8a4a1d]" : score >= 40 ? "border-[#b3792e] text-[#8a571b]" : "border-[#858a82] text-[#626760]"; return <span className={`mono-number whitespace-nowrap border-l-2 px-2 py-0.5 text-xs font-bold ${style}`}>{score}<span className="ml-1 font-sans text-[9px] font-semibold uppercase tracking-wide">opp.</span></span>; }
function LeadStatusBadge({ status }: { status: LeadStatus }) { const style = status === "converted" ? "border-[#176b5b] text-[#176b5b]" : status === "interested" ? "border-[#3f6b68] text-[#355b58]" : status === "contacted" ? "border-[#81642e] text-[#725725]" : status === "not_interested" ? "border-[#858a82] text-[#737870]" : "border-[#aeb1a9] text-[#4d524c]"; return <span className={`whitespace-nowrap border-l-2 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${style}`}>{status.replace("_", " ")}</span>; }
function ScoreRing({ score }: { score: number }) { const style = score >= 80 ? "border-[#a33b32] text-[#8f332c]" : score >= 60 ? "border-[#b06228] text-[#8a4a1d]" : score >= 40 ? "border-[#b3792e] text-[#8a571b]" : "border-[#858a82] text-[#626760]"; return <span className={`mono-number grid h-9 w-10 shrink-0 place-items-center border-l-2 text-xs font-bold ${style}`}>{score}</span>; }
function CompactSelect({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[][] }) { return <select className="h-9 border border-[#c8cac2] bg-[#fffefa] px-3 text-xs font-medium text-[#4d524c]" value={value} onChange={(e) => onChange(e.target.value)}>{options.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="border-l border-[#d5d5cd] px-3 first:border-l-0"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#737870]">{label}</p><p className="mono-number mt-1 text-sm font-bold">{value}</p></div>; }
function Info({ icon: Icon, text }: { icon: typeof MapPin; text: string }) { return <div className="flex items-start gap-3 text-sm text-gray-600"><Icon size={16} className="mt-0.5 shrink-0 text-gray-400"/><span className="break-all">{text}</span></div>; }
function Timeline({ label, time }: { label: string; time: string }) { return <div className="relative"><span className="absolute -left-[22px] top-1 h-2 w-2 bg-[#176b5b]"/><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-[#737870]">{formatDate(time)}</p></div>; }
function SettingsCard({ icon: Icon, title, text, children }: { icon: typeof Settings; title: string; text: string; children: React.ReactNode }) { return <section className="grid border-t border-[#d5d5cd] py-6 md:grid-cols-[220px_1fr] md:gap-8"><div className="mb-4 flex items-start gap-3 md:mb-0"><Icon size={17} className="mt-0.5 text-[#176b5b]"/><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs leading-5 text-[#737870]">{text}</p></div></div><div>{children}</div></section>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
